#+TITLE: Nextflow with AWS Batch: A Worked Example

* Introduction
** Requirements

- MAFFT
- FastTree

* Using Nextflow Locally

Let's try to construct a phylogenetic tree based on orthologs of the human haemogoblin alpha 1 subunit.

- Humans, HBA1 or [[https://asia.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000206172;r=16:176680-177522][ENSG00000206172]].
- Mice, Hba-a1 or [[https://asia.ensembl.org/Mus_musculus/Gene/Summary?g=ENSMUSG00000069919;r=11:32283511-32284465][ENSMUSG00000069919]].
- Zebrafish, zgc:163057 or [[https://asia.ensembl.org/Danio_rerio/Gene/Summary?g=ENSDARG00000045144;r=12:20336070-20337274;t=ENSDART00000066385][ENSDARG00000045144]].

Download those gene sequences and combine them into a single fasta file, [[hba1.fasta.gz]].

# We could write a few paragraphs here that slowly build up toward hba-local.nf.

In the end, you should end up with a file like [[hba-local.nf]].

* Using Nextflow with Docker Containers

Simply add the appropriate ~container~ directive to each process:

#+begin_src
process alignMultipleSequences {
    container "biocontainers/mafft:v7.407-2-deb_cv1"

    // ...
}

process buildTree {
    container "biocontainers/fasttree:v2.1.10-2-deb_cv1"
    publishDir './'

    // ...
}
#+end_src

You should have a nextflow script which looks like [[hba-docker.nf]].
And also create a new file, [[nextflow.config]] which looks like:

#+begin_src
profiles {
    docker {
        docker.enabled = true
    }
}
#+end_src

Now, using the same command ~nextflow run hba-docker.nf~ will /not/ cause Nextflow to use docker.
You must also specify using the ~-profile docker~ command line argument that docker /should/ be used.

#+begin_src bash
nextflow run hba-docker.nf -profile docker
#+end_src

* Using Nextflow with AWS S3

This is as simple as adding the ~s3~ protocol to the input file path:

#+begin_src
hbaSequences = Channel.fromPath("s3://nextflow-awsbatch/hba1.fasta.gz")
#+end_src

And doing the same for the publish directory:

#+begin_src
process buildTree {
    container "biocontainers/fasttree:v2.1.10-2-deb_cv1"
    publishDir "s3://nextflow-awsbatch/"

    /...
}
#+end_src

You should have a Nextflow script that looks like [[hba-s3.nf]].

* Using Nextflow with AWS Batch
* A larger example: COVID-19 in Singapore
* Changes
** 28 Oct 2020 - Marcus
- Addition of `awsbatch` profile to the configuration file
